name: Go Build Multi-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          # Add exclusions if certain combinations are not needed or supported
          # Example: Exclude windows/arm64 if not targeted
          # - goos: windows
          #   goarch: arm64

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        output_name="arcgis-utils-go-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name+=".exe"
        fi
        go build -v -o "${output_name}" .
        echo "Built: ${output_name}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: arcgis-utils-go-${{ matrix.goos }}-${{ matrix.goarch }}
        path: arcgis-utils-go-${{ matrix.goos }}-${{ matrix.goarch }}*